language: node_js
sudo: required
services:
  - docker
install:
  - npm install -g npm@latest
  - npm install -g chimera-cli
  - git clone https://github.com/TryGhost/Ghost.git --depth 1 --recursive
script:
  - chimera -p Ghost/
env:
  matrix:
    - CHIMERA_TARGET=ubuntu:14.04
    - CHIMERA_TARGET=ubuntu:15.10
    - CHIMERA_TARGET=fedora:22
    - CHIMERA_TARGET=fedora:23
    - CHIMERA_TARGET=centos:7
    - CHIMERA_TARGET=opensuse:13.2
    - CHIMERA_TARGET=debian:8
    - CHIMERA_TARGET=arch:latest
